from datetime import datetime

# SCOPE
LIST_OF_STOCKS = ["MSFT", "AAPL", "NVDA", "AMZN", "GOOG", "META", "TSLA"]
BACKTEST_START = datetime(1981, 1, 1)
BACKTEST_END = datetime(2023, 12, 31)

# TRADING SETUP & CONSTRAINTS
CAPITAL_0 = 1e6
COMMISSION_RATE = .0010
SLIPPAGE_RATE = .0002
MIN_TRANSC = 10
MAX_PROP = .30
RISK_FREE_RATE = .02
BUSINESS_DAYS = 252